#!/usr/bin/zsh
# Options
# Share history betwen multiple termional sessions
# setopt share_history # I prefer separate history lmao
# Append history, instead of replace, when a terminal session exits
setopt appendhistory
# Add commands as they are typed, don't wait until shell exit
setopt inc_append_history
# Ignore commands with a space before
setopt hist_ignore_space
# Remove the old entry and append the new one
setopt hist_ignore_all_dups
# When searching history don't display results already cycled through twice
setopt hist_find_no_dups
# Remove extra blanks from each command line being added to history
setopt hist_reduce_blanks
# Add timestamps to history
setopt extended_history
#notify on job completion
setopt notify
# list jobs in the long format
setopt long_list_jobs
# don't kill background jobs on logout
setopt nohup
# allow functions to have local options
setopt local_options
# allow functions to have local traps
setopt local_traps
# required for alias completion: m c<TAB>
setopt complete_aliases
# complete in the middle of a word
setopt complete_in_word
# prompt substitution seems to have turned off..
setopt prompt_subst
# END OPTIONS
